# Generated by Django 5.1.2 on 2024-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='issuedboook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=200)),
                ('reader_name', models.CharField(max_length=200)),
                ('reader_email', models.CharField(max_length=200)),
                ('bookid', models.CharField(max_length=20)),
                ('bookname', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('issueddate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=200)),
                ('reader_name', models.CharField(max_length=200)),
                ('reader_email', models.CharField(max_length=200)),
                ('reader_contact', models.CharField(max_length=200)),
                ('reader_dept', models.CharField(max_length=200)),
                ('reader_batch', models.CharField(max_length=200)),
            ],
        ),
    ]
