# Generated by Django 5.1.2 on 2024-11-01 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedboook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 8, 10, 28, 54, 70406, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='issuedboook',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
