# Generated by Django 5.1.2 on 2024-11-02 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_issuedboook_due_date_issuedboook_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedboook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 9, 12, 2, 9, 450665, tzinfo=datetime.timezone.utc)),
        ),
    ]
