# Generated by Django 5.1.2 on 2024-11-03 05:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_issuedboook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Author name can only contain letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Book name can only contain letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='issuedboook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 10, 5, 38, 17, 505658, tzinfo=datetime.timezone.utc)),
        ),
    ]
