# Generated by Django 5.1.2 on 2024-11-05 02:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_book_author_alter_book_bookname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedboook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issuedboook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 2, 11, 20, 941367, tzinfo=datetime.timezone.utc)),
        ),
    ]
