# Generated by Django 5.1.2 on 2024-11-05 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_issuedboook_user_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedboook',
            name='user',
        ),
        migrations.AlterField(
            model_name='issuedboook',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 3, 17, 51, 71387, tzinfo=datetime.timezone.utc)),
        ),
    ]
